### ISSUE TITLE
A problem about DiffusionNet

### ISSUE THREAD

**Issue by JiachengDeng** [dongliangcao/Self-Supervised-Multimodal-Shape-Matching#3]
Hi Dongliang,

First of all, I appreciate your patience in answering my last question. 

Another problem I have encountered is about DiffusionNet. In the training yaml file, you mentioned the "... /data/surreal5k/diffusion" directory, which I know is DiffusionNet related, and thank you for providing the link to the corresponding repository. But I would like to ask which files of the model should be placed in this directory and exactly how to configure it to ensure that your model can be trained properly?

`# network setting 
networks:  
  feature_extractor:  
    type: DiffusionNet 
    in_channels: 3 
    out_channels: 128 
    cache_dir: ../data/surreal5k/diffusion 
  fmap_net: 
    type: RegularizedFMNet 
    bidirectional: true 
  permutation: 
    type: Sinkhorn 
    num_sink: 10 
    lambda_sink: 0.2`

**Comment by dongliangcao** [comment]
Hi Jiacheng,

It is also related to the data pre-processing. There are two ways to solve this problem.
1) Using `python preprocess.py ../data/surreal5k --no_normalize --no_dist --n_eig 128` to pre-compute the LBO eigenfunctions for SURREAL-5K dataset.
2) Simple create ../data/surreal5k/diffusion as an empty folder, during training the DiffusionNet will try to find the corresponding LBO eigenfunctions for each shape under this folder, if it doesn't find it, it will compute them and store them under this folder to avoid re-computing.
