### ISSUE TITLE
About the Pyx calculation in "mesh" mode and "point cloud" mode

### ISSUE THREAD

**Issue by yjzhang96** [dongliangcao/Self-Supervised-Multimodal-Shape-Matching#6]
Hi, I had a few questions about the Pyx in your code and I hope you can give some insight for me!

First, What is the physical meaning of 'Pyx'? 
Second, why is the Pyx calculated in different ways between "mesh" mode and "point cloud" mode? I noticed Pyx is used for calculating p2p in "point cloud" mode. Is Pyx in "mesh" mode can also used for calculating p2p? 

Thanks in advance for your help!

**Comment by dongliangcao** [comment]
Thanks for your interest. The Pyx is a _soft_ point-wise correspondence matrix with the shape $N_y \times N_x$. During inference, if the input shapes are meshes, the method uses standard functional map pipeline to obtain the final p2p, while if the input shapes are point clouds, the method uses nearest neighbor search on the feature domain to obtain the final p2p. More details can be found in the corresponding paper.

**Comment by yjzhang96** [comment]
Thanks for the reply! 

So if my understanding is correct, Pyx in the functional map pipeline ` Pyx = evecs_y.squeeze() @ Cxy.squeeze() @ evecs_trans_x.squeeze()` is another way to calculate the final p2p (if we apply argmax func as in point cloud mode), yet the accuracy is not as high as the p2p calculated from functional map.

Is it reasonable that the results of p2p and Pyx are very different? Cause this is what I observed in my test data

**Comment by dongliangcao** [comment]
Yes, it is reasonable. Because the purpose of this code `Pyx = evecs_y.squeeze() @ Cxy.squeeze() @ evecs_trans_x.squeeze()` is to create a soft point-wise correspondence for **more smooth** texture transfer but not for obtaining a more accurate p2p
